### ISSUE TITLE
What the stack‽

### ISSUE THREAD

**Issue by CAD97** [rust-lang/project-inline-asm#2]
[Initially raised in the context of `call`.](https://internals.rust-lang.org/t/pre-rfc-2-inline-assembly/11310/156?u=cad97)

As I understand it, there are five main options that inline asm can guarantee for the stack (pointer) when entering inline asm, in order of increasing developer convenience and compiler restriction:

- The stack pointer is not guaranteed to live in the stack pointer register. `push`/`pop` are not allowed in the inline asm, and any use of the stack is impossible.
- The stack pointer lives in the stack pointer register, but has no specified value. Essentially the same as the previous; the stack is unusable. This option is strictly worse than the previous option as it is more restrictive to the compiler without any developer benefit.
- The stack pointer lives in the stack pointer register, and it is guaranteed to be "valid" for the current stack usage. In practical language, this means that "most" of the stack data is in the stack. However, some stack items may be in the space beyond the stack pointer, so using `push`/`pop` is still not allowed. However, with [not a small amount of ceremony](https://stackoverflow.com/a/37503773/3019990), it is possible for inline asm to jump the stack pointer over the "red zone" and realign the stack pointer such that the use of the stack (i.e. `push`/`pop`) is possible.
- The stack pointer lives in the stack pointer and all stack data currently in use is in the stack. The space beyond the stack is free for the inline asm to use (i.e. an immediate `push` is allowed), but there is no alignment guarantee on the stack pointer.
- The same as the last, but the stack pointer is guaranteed to be aligned to some N, probably the alignment required by the system ABI to call functions. IIUC, this is roughly `alignstack` in LLVM.

The postcondition for inline asm is obviously clear: the stack pointer must be restored to the initial value and all stack values in use by the compiler must be restored to their initial value as well. (For option three, this means if you touch the stack, skip over the "red zone". For option four/five, this means don't `pop` the stack more than you `push` it.)

**Comment by Amanieu** [comment]
I'm currently tending towards supporting calls in inline asm, since this is common thing that people will try to do and the bugs they will encounter if we don't support it will be extremely subtle. In fact even glibc used to have calls from inline asm before [the gcc folks told them it was a bad idea](https://sourceware.org/bugzilla/show_bug.cgi?id=20965) (the bug is still open but most of the code they refer to has been fixed since).

Regarding the exact semantics, I would like the default to be the most convenient: on entry to the asm block, you are free to use any memory below the stack pointer and the stack pointer is guaranteed to be suitably aligned for a function call. This is essentially what LLVM's `alignstack` attribute gives us.

A `nostack` flag will be added which removes all of the above guarantees: asm blocks using it are not allowed to touch any stack memory, whether above or below the stack pointer. They can still inspect the stack pointer, e.g. for determining which thread they are on. This isn't really restricting the compiler since the stack pointer is generally mandated to be "correct" by the platform ABI.

**Comment by Amanieu** [comment]
There is the obvious downside that `alignstack` isn't really supported by GCC. However work on the Rust GCC backend has only just begun, and I think that by the time this becomes an issue we can look into getting some equivalent of `alignstack` added to GCC.

**Comment by CAD97** [comment]
> you are free to use any memory below the stack pointer

Note that this isn't 100% true as written: if you leave the red zone, interrupts may trample over your oversized stack. If you need more space than that, you have to adjust the stack pointer; that's a requirement of the system, not of us, though.

**Comment by joshtriplett** [comment]
I agree that we should default to `alignstack` and have a `nostack` to allow more optimization at the risk of "you have to meet the conditions".

I also think, for the moment, that whether you use `nostack` or not we should state explicitly that you cannot safely use the red zone in inline assembly. If in the future there's a use case for supporting that, and a means of telling LLVM or other backends that inline assembly has done so, we could define a mechanism to expose that.

**Comment by Amanieu** [comment]
> I also think, for the moment, that whether you use nostack or not we should state explicitly that you cannot safely use the red zone in inline assembly. If in the future there's a use case for supporting that, and a means of telling LLVM or other backends that inline assembly has done so, we could define a mechanism to expose that.

I don't think that this is an issue: the `alignstack` attribute guarantees that there is no useful data below the stack pointer (since the state is suitable for a call instruction), so the asm code is free to use the red zone in that case.
